<?php
return array (
  'MODULE_ALLOW_LIST' => 
  array (
    0 => 'Home',
    1 => 'Admin',
    2 => 'Weixin',
    3 => 'Mobile',
    4 => 'Apk',
    5 => 'Jobfair',
    6 => 'Mall',
    7 => 'Store',
    8 => 'Parttime',
    9 => 'Gworker',
    10 => 'House',
    11 => 'School',
    12 =>'Allowance',
    13 =>'Appapi',
    14 =>'Career',
    15 =>'Crm',
    16 =>'Employer',
    17 =>'Interview',
    18 =>'Jobclickup',
    19 =>'Qqfloat',
    20 =>'Resumeimport',
    21 =>'Rpo',
    22 =>'Statistics',
    23 =>'Sincerity',
    24 =>'Subject',
    25 =>'Weixinapp',
    26 =>'Analyze',
    27 =>'Beautyhr',
    28 =>'Export',
    29 =>'Locoyspider',
    30 =>'Magappx',
    31 =>'Qianfanyunapp',
  ),
  'MODULE_DENY_LIST' => 
  array (
    0 => 'Common',
  ),
  'DEFAULT_MODULE' => 'Home',
  'TAGLIB_PRE_LOAD' => 'qscms',
  'DEFAULT_FILTER' => 'htmlspecialchars,stripslashes,strip_tags',
  'TMPL_ACTION_SUCCESS' => 'public:showmsg',
  'TMPL_ACTION_ERROR' => 'public:showmsg',
  'LANG_SWITCH_ON' => true,
  'DEFAULT_LANG' => 'zh-cn',
  'LANG_AUTO_DETECT' => true,
  'LANG_LIST' => 'zh-cn',
  'LOAD_EXT_CONFIG' => 'url,db,cache,tags,sub_domain,pwdhash,html_cache',
  'CRON_ON' => true,
  'DATA_CACHE_SUBDIR' => true,
  'DATA_PATH_LEVEL' => 3,
  'TMPL_DETECT_THEME' => true,
  'APP_SUB_DOMAIN_DEPLOY' => true,
  'TOKEN_ON' => false,
  'TOKEN_NAME' => '__hash__',
  'TOKEN_TYPE' => 'md5',
  'TOKEN_RESET' => true,
  'DB_FIELDTYPE_CHECK' => true,
  'OUTPUT_ENCODE' => true,
  'PWD_ENCRYPT_METHOD' => 0,
  'COOKIE_HTTPONLY'=>true,
  'VERIFY_NUM_CHECK'=>5,
);
?>