--

--
-- 转存表中的数据 `qs_config`
--

INSERT INTO `qs_config` (`id`, `name`, `value`, `note`, `type`) VALUES
(NULL, 'wap_domain', '', '触屏版域名', 'Mobile'),
(NULL, 'mobile_captcha_open', '0', '是否开启触屏端极验', 'Mobile'),
(NULL, 'mobile_isclose', '0', '触屏端是否关闭', 'Mobile'),
(NULL, 'mobile_close_reason', '测试中', '触屏站点关闭原因', 'Mobile'),
(NULL, 'mobile_statistics', '', '触屏端站点统计', 'Mobile'),
(NULL, 'mobile_closereg', '0', '触屏端关闭注册', 'Mobile'),
(NULL, 'resume_base', '10000', '简历数量基值', 'Mobile'),
(NULL, 'jobs_base', '10000', '职位数量基值', 'Mobile'),
(NULL, 'footer_nav_status', '0', '触屏端底部导航上否开启', 'Mobile'),
(NULL, 'wap_captcha_config', 'a:3:{s:10:"varify_reg";s:1:"1";s:13:"varify_mobile";s:1:"1";s:10:"user_login";s:1:"3";}', '触屏极验配置', 'Mobile'),
(NULL, 'page_full_screen', '1', '页面是否全屏显示','Mobile'),
(NULL, 'm_template_dir', 'default', '触屏端模板切换', 'Mobile'),
(NULL, 'mobile_setmeal_discount_type', '0', '触屏版购买套餐优惠类型', 'Mobile'),
(NULL, 'mobile_setmeal_discount_value', '0', '触屏版购买套餐优惠', 'Mobile'),
(NULL, 'mobile_setmeal_increment_discount_type', '0', '触屏版购买增值服务优惠类型', 'Mobile'),
(NULL, 'mobile_setmeal_increment_discount_value', '0', '触屏版购买增值服务优惠', 'Mobile'),
(NULL, 'mobile_discount_qrcode_url', '', '优惠引导二维码url', 'Mobile'),
(NULL, 'refresh_jobs_more', '0', '触屏版刷新职位额外次数', 'Mobile'),
(NULL, 'logo_mobile', 'logo_mobile.png', '触屏logo', 'Mobile'),
(NULL, 'mobile_top_color', '', '触屏顶部背景色', 'Mobile'),
(NULL, 'mobile_index_jobs_type', 'new', '首页职位推荐类型', 'Mobile'),
(NULL, 'mobile_index_login_recommend', '1', '登录开启千人千面', 'Mobile'),
(NULL, 'wzp_share_title', '', 'H5微信招聘分享标题', 'Mobile'),
(NULL, 'wzp_share_desc', '', 'H5微信招聘分享描述', 'Mobile'),
(NULL, 'wzp_share_img', '', 'H5微信招聘分享图片', 'Mobile'),
(NULL, 'weixin_service_img', '', '触屏客服二维码', 'Mobile');

--
-- 转存表中的数据 `qs_page`
--

INSERT INTO `qs_page` VALUES 
(NULL,1,1,'QS_index','网站首页','Mobile','Index','index','',0,0,'Index','骑士人才系统','骑士CMS是基于PHP+MYSQL的免费网站管理系统，提供完善的人才招聘网站建设方案','骑士人才系统，74cms，骑士cms，人才网站源码，php人才网程序','','Mobile'),
(NULL,1,2,'QS_jobslist','职位列表页','Mobile','Jobs','index','',0,0,'jobs','全职','','','a:3:{s:11:\"jobcategory\";s:12:\"职位分类\";s:12:\"citycategory\";s:12:\"地区分类\";s:3:\"key\";s:9:\"关健字\";}','Mobile'),
(NULL,1,3,'QS_jobsshow','招聘详细页','Mobile','Jobs','show','',0,0,'jobs','{jobs_name} ','{companyname}招聘岗位,{jobs_name}','{companyname},{jobs_name},{nature_cn},{category_cn},{district_cn}','a:8:{s:9:\"jobs_name\";s:12:\"职位名称\";s:11:\"companyname\";s:12:\"公司名称\";s:6:\"sex_cn\";s:6:\"性别\";s:9:\"nature_cn\";s:12:\"工作性质\";s:11:\"category_cn\";s:12:\"职位类别\";s:8:\"trade_cn\";s:6:\"行业\";s:11:\"district_cn\";s:6:\"地区\";s:12:\"education_cn\";s:6:\"学历\";}','Mobile'),
(NULL,1,3,'QS_companyshow','企业简介页','Mobile','Jobs','comshow','',0,0,'jobs','{companyname}','{contents},公司简介','{companyname},公司简介','a:7:{s:11:\"companyname\";s:12:\"公司名称\";s:9:\"nature_cn\";s:12:\"公司性质\";s:11:\"category_cn\";s:12:\"职位类别\";s:8:\"trade_cn\";s:12:\"公司行业\";s:11:\"district_cn\";s:12:\"所在地区\";s:8:\"scale_cn\";s:12:\"公司规模\";s:8:\"contents\";s:12:\"公司介绍\";}','Mobile'),
(NULL,1,1,'QS_login','会员登录','Mobile','Members','login','',0,0,'members','会员登录','','','','Mobile'),
(NULL,1,2,'QS_resumelist','简历列表','Mobile','Resume','index','',0,0,'Resume','简历','','','a:3:{s:11:\"jobcategory\";s:12:\"职位分类\";s:12:\"citycategory\";s:12:\"地区分类\";s:3:\"key\";s:9:\"关健字\";}','Mobile'),
(NULL,1,3,'QS_resumeshow','简历详细页','Mobile','Resume','show','',0,0,'Resume','{fullname}的简历','{title},{fullname},{specialty}','{fullname},{sex_cn},{nature_cn},{trade_cn},{district_cn},{wage_cn},{education_cn},{major_cn},{intention_jobs}','a:11:{s:5:\"title\";s:12:\"简历标题\";s:8:\"fullname\";s:12:\"真实姓名\";s:6:\"sex_cn\";s:6:\"性别\";s:9:\"nature_cn\";s:12:\"工作性质\";s:8:\"trade_cn\";s:12:\"意向行业\";s:11:\"district_cn\";s:12:\"意向地区\";s:7:\"wage_cn\";s:12:\"期望薪资\";s:12:\"education_cn\";s:6:\"学历\";s:8:\"major_cn\";s:6:\"专业\";s:14:\"intention_jobs\";s:12:\"期望职位\";s:9:\"specialty\";s:12:\"自我描述\";}','Mobile'),
(NULL,1,2,'QS_newslist','资讯列表','Mobile','News','index','',0,0,'news','资讯','','','a:2:{s:3:\"key\";s:9:\"关键字\";s:12:\"categoryname\";s:12:\"分类名称\";}','Mobile'),
(NULL,1,3,'QS_newsshow','资讯详细页','Mobile','News','show','',0,0,'news','{title}','{seo_description}','{seo_keywords}','a:3:{s:5:\"title\";s:12:\"文章标题\";s:12:\"seo_keywords\";s:18:\"Seo优化关键字\";s:15:\"seo_description\";s:16:\"Seo 优化描述\";}','Mobile'),
(NULL,1,3,'QS_noticeshow','公告详细页','Mobile','Notice','show','',0,0,'notice','{title}','{seo_description}','{seo_keywords}','a:3:{s:5:\"title\";s:12:\"文章标题\";s:12:\"seo_keywords\";s:18:\"Seo优化关键字\";s:15:\"seo_description\";s:16:\"Seo 优化描述\";}','Mobile'),
(NULL,1,1,'QS_mall_index','积分商城首页','Mobile','Mall','index','',0,0,'shop','积分商城','','','','Mobile'),
(NULL,1,2,'QS_goods_list','积分商城列表页','Mobile','Mall','plist','',0,0,'shop_list','积分商城{key}','','','a:1:{s:3:\"key\";s:9:\"关键字\";}','Mobile'),
(NULL,1,4,'QS_goods_exchange','兑换商品','Mobile','Mall','create_order','',0,0,'shop_list','兑换商品','','','','Mobile'),
(NULL,1,3,'QS_goods_show','积分商城详细页面','Mobile','Mall','show','',0,0,'shop_list','积分商城','{content}','{category_cn},{goods_title},{goods_brand}','a:4:{s:11:\"category_cn\";s:12:\"分类名称\";s:11:\"goods_title\";s:12:\"商品名称\";s:7:\"content\";s:12:\"商品描述\";s:11:\"goods_brand\";s:12:\"商品品牌\";}','Mobile'),
(NULL,1,5,'QS_mall_order_list','兑换记录','Mobile','Mall','order_list','',0,0,'shop_list','兑换记录','','','','Mobile'),
(NULL,1,6,'QS_mall_order_show','兑换详情','Mobile','Mall','order_show','',0,0,'shop_list','兑换详情','','','','Mobile'),
(NULL,1,2,'QS_jobfairexhibitors','参会企业列表','Mobile','Jobfair','comlist','',0,0,'jobfair','参会企业','{introduction},{address},{bus}','{title},{address},{bus}','a:5:{s:5:\"title\";s:15:\"招聘会标题\";s:12:\"introduction\";s:15:\"招聘会简介\";s:7:\"address\";s:12:\"举办地址\";s:3:\"bus\";s:12:\"乘车路线\";s:6:\"number\";s:9:\"展位数\";}','Mobile'),
(NULL,1,3,'QS_jobfairshow','招聘会详细页','Mobile','Jobfair','show','',0,0,'jobfair','{title}','{introduction},{address},{bus}','{title},{address},{bus}','a:5:{s:5:\"title\";s:15:\"招聘会标题\";s:12:\"introduction\";s:15:\"招聘会简介\";s:7:\"address\";s:12:\"举办地址\";s:3:\"bus\";s:12:\"乘车路线\";s:6:\"number\";s:9:\"展位数\";}','Mobile'),
(NULL,1,2,'QS_jobfairlist','招聘会列表','Mobile','Jobfair','index','',0,0,'jobfair','招聘会','','','','Mobile'),
(NULL,1,6,'QS_jobfairreserve','在线预定页','Mobile','Jobfair','reserve','',0,0,'jobfair','在线预定','','','','Mobile'),
(NULL,1,3,'QS_company_report','企业实地认证报告','Mobile','Jobs','com_report','',0,0,'jobs','企业实地认证报告','企业实地认证报告,{com_name},{site_name},{evaluation}','企业实地认证报告,{com_name},{site_name}','a:2:{s:8:\"com_name\";s:12:\"企业名称\";s:10:\"evaluation\";s:12:\"认证评价\";}','Mobile'),
(NULL,1,3,'QS_career_show','事业单位招考详情页','Mobile','Career','show','',0,0,'Career','事业单位招考详情页 - {site_name}','','','','Mobile'),
(NULL,1,2,'QS_career_list','事业单位招考列表','Mobile','Career','index','',0,0,'Career','事业单位招考列表 - {site_name}','','','','Mobile'),
(NULL,1,1,'QS_gworker','普工首页','Mobile','Gworker','index','',0,0,'gworker','普工招聘','','','','Mobile'),
(NULL,1,1,'QS_gworker_show','普工招聘详细页','Mobile','Gworker','show','',0,0,'gworker','{jobs_name}','{jobs_name}','{jobs_name},{district_cn}','','Mobile'),
(NULL,1,1,'QS_house_rent','房屋出租','Mobile','House','index','',0,0,'house','房屋出租','','','','Mobile'),
(NULL,1,1,'QS_house_seek','房屋求租','Mobile','House','seek','',0,0,'house','房屋求租','','','','Mobile'),
(NULL,1,1,'QS_house_rent_show','房屋出租详细页','Mobile','House','show_rent','',0,0,'house','{title}','{title}','{title}，{district_cn}','','Mobile'),
(NULL,1,1,'QS_house_seek_show','房屋求租详细页','Mobile','House','show_seek','',0,0,'house','{title}','{title}','{title}，{district_cn}','','Mobile'),
(NULL,1,3,'QS_interview_show','专访详细页','Mobile','Interview','show','',0,0,'interview','企业专访详细页 - {site_name}','','','','Mobile'),
(NULL,1,2,'QS_interview_list','专访列表','Mobile','Interview','index','',0,0,'interview','企业专访列表 - {site_name}','','','','Mobile'),
(NULL,1,1,'QS_parttime','兼职首页','Mobile','Parttime','index','',0,0,'parttime','兼职招聘','','','','Mobile'),
(NULL,1,1,'QS_parttime_show','兼职招聘详细页','Mobile','Parttime','show','',0,0,'parttime','{jobs_name}','{jobs_name}','{jobs_name},{category_cn},{district_cn}','','Mobile'),
(NULL,1,1,'QS_school_index','校园招聘','Mobile','School','index','',0,0,'school','校园招聘 - {site_name}','','','','Mobile'),
(NULL,1,2,'QS_school_school','院校','Mobile','School','school','',0,0,'school','院校 - 校招 - {site_name}','','','','Mobile'),
(NULL,1,2,'QS_school_career_talk','宣讲会','Mobile','School','career_talk','',0,0,'school','宣讲会 - {site_name}','','','','Mobile'),
(NULL,1,2,'QS_school_double_election','双选会','Mobile','School','double_election','',0,0,'school','双选会 - {site_name}','','','','Mobile'),
(NULL,1,2,'QS_school_school_election','院校双选会','Mobile','School','school_election','',0,0,'school','{name} - 双选会 - {site_name}','','','a:1:{s:4:\"name\";s:12:\"院校名称\";}','Mobile'),
(NULL,1,2,'QS_school_school_talk','院校宣讲会','Mobile','School','school_talk','',0,0,'school','{name} - 宣讲会 - {site_name}','','','a:1:{s:4:\"name\";s:12:\"院校名称\";}','Mobile'),
(NULL,1,3,'QS_school_talk_info','宣讲会详细','Mobile','School','talk_info','',0,0,'school','{subject} - 宣讲会 - {site_name}','','','a:1:{s:7:\"subject\";s:12:\"主题名称\";}','Mobile'),
(NULL,1,3,'QS_school_election_info','双选会详细','Mobile','School','election_info','',0,0,'school','{subject} - 双选会 - {site_name}','','','a:1:{s:7:\"subject\";s:12:\"主题名称\";}','Mobile'),
(NULL,1,3,'QS_school_school_show','院校详细','Mobile','School','school_show','',0,0,'school','{name} - 院校 - {site_name}','','','a:1:{s:4:\"name\";s:12:\"院校名称\";}','Mobile'),
(NULL,1,1,'QS_storerecruit','门店招聘','Mobile','Storerecruit','index','',0,0,'store','门店招聘','','','','Mobile'),
(NULL,1,1,'QS_storetransfer','门店转让','Mobile','Storetransfer','index','',0,0,'store','门店转让','','','','Mobile'),
(NULL,1,1,'QS_storetenement','门店求租','Mobile','Storetenement','index','',0,0,'store','门店求租','','','','Mobile'),
(NULL,1,1,'QS_storerecruit_show','门店招聘详细页','Mobile','Storerecruit','show','',0,0,'store','{jobs_name}','{jobs_name}','{jobs_name},{category_cn},{district_cn}','','Mobile'),
(NULL,1,1,'QS_storetransfer_show','门店转让详细页','Mobile','Storetransfer','show','',0,0,'store','{title}','{title}','{title},{category_cn},{district_cn}','','Mobile'),
(NULL,1,1,'QS_storetenement_show','门店求租详细页','Mobile','Storetenement','show','',0,0,'store','{title}','{title}','{title},{category_cn},{district_cn}','','Mobile'),
(NULL,1,3,'QS_subject_show','网络专题招聘会详情页','Mobile','subject','show','',0,0,'Subject','网络专题招聘会详情页 - {site_name}','','','','Mobile'),
(NULL,1,2,'QS_subject_list','网络专题招聘会列表','Mobile','subject','index','',0,0,'Subject','网络专题招聘会列表 - {site_name}','','','','Mobile');
